krisha_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      pass: dimashprpr
      port: 5432
      dbname: krisha_data
      schema: public
